apiVersion: v1
kind: Service
metadata:
  name: nats
  labels:
    component: nats
spec:
  selector:
    component: nats
  clusterIP: None
  ports:
  - name: client
    port: 4222
    protocol: TCP
  - name: cluster
    port: 6222
    protocol: TCP
  - name: monitor
    port: 8222
    protocol: TCP
